package Parser;
/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUALS = 1;
  /** RegularExpression Id. */
  int NEGATION = 2;
  /** RegularExpression Id. */
  int LBRACE = 3;
  /** RegularExpression Id. */
  int RBRACE = 4;
  /** RegularExpression Id. */
  int P_OPEN = 5;
  /** RegularExpression Id. */
  int P_CLOSE = 6;
  /** RegularExpression Id. */
  int B_OPEN = 7;
  /** RegularExpression Id. */
  int B_CLOSE = 8;
  /** RegularExpression Id. */
  int POINT = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int CLOSER = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int EXTENDS = 15;
  /** RegularExpression Id. */
  int RETURN = 16;
  /** RegularExpression Id. */
  int CLASS = 17;
  /** RegularExpression Id. */
  int PUBLIC = 18;
  /** RegularExpression Id. */
  int STATIC = 19;
  /** RegularExpression Id. */
  int VOID = 20;
  /** RegularExpression Id. */
  int MAIN = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int ARRAY_MODIFIER = 24;
  /** RegularExpression Id. */
  int LENGTH = 25;
  /** RegularExpression Id. */
  int BOOLEAN = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int FALSE = 28;
  /** RegularExpression Id. */
  int THIS = 29;
  /** RegularExpression Id. */
  int NEW = 30;
  /** RegularExpression Id. */
  int END = 31;
  /** RegularExpression Id. */
  int OP = 32;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int ID = 35;
  /** RegularExpression Id. */
  int LIT = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"extends\"",
    "\"return\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"int\"",
    "\"[]\"",
    "\"length\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"$\"",
    "<OP>",
    "<INTEGER_LITERAL>",
    "<DIGIT>",
    "<ID>",
    "<LIT>",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
    "<token of kind 40>",
    "<token of kind 41>",
    "\"System.out.println\"",
  };

}
